# Generated by Django 6.0.2 on 2026-02-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0002_blocktemplate_blocktemplateday_blocktemplatelift'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(help_text='Day number in the block, e.g. 1 for Day 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.liftcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0, help_text='Order of the lift within the day, starting from 0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='lifts.lifttemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='BlockPrompt',
        ),
        migrations.RemoveField(
            model_name='blocktemplateday',
            name='template',
        ),
        migrations.RemoveField(
            model_name='blocktemplatelift',
            name='day',
        ),
        migrations.DeleteModel(
            name='BlockTemplate',
        ),
        migrations.DeleteModel(
            name='BlockTemplateDay',
        ),
        migrations.DeleteModel(
            name='BlockTemplateLift',
        ),
    ]
