# Generated by Django 6.0.2 on 2026-02-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0003_liftcategory_lifttemplate_savedlift_templatelift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlift',
            name='variation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='lifts.savedlift'),
        ),
    ]
