# Generated by Django 6.0.2 on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifts", "0004_savedlift_variation_of"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lifttemplate",
            old_name="date",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="lifttemplate",
            name="name",
            field=models.CharField(
                help_text="Favorite day name, e.g. Pull Day",
                max_length=255,
            ),
        ),
    ]
