# Generated by Django 6.0.2 on 2026-02-08 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0005_rename_lifttemplate_date_to_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('intensity', models.CharField(choices=[('minor', 'Minor'), ('medium', 'Medium'), ('high', 'High'), ('non-relevant', 'Non-relevant')], default='non-relevant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDayLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order of the lift within the training day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='lifts.trainingday')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
