# Generated by Django 6.0.2 on 2026-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifts", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingdaylift",
            name="is_pr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainingdaylift",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
