# Generated by Django 6.0.4 on 2026-04-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0008_trainingdaylift_is_pr_trainingdaylift_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatelift',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AddField(
            model_name='savedlift',
            name='default_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedlift',
            name='default_sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedlift',
            name='default_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='templatelift',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatelift',
            name='saved_lift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_lifts', to='lifts.savedlift'),
        ),
        migrations.AddField(
            model_name='templatelift',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatelift',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='trainingday',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingdaylift',
            name='saved_lift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_day_lifts', to='lifts.savedlift'),
        ),
    ]
